on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      release_name: ${{ github.event.repository.name }}_${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create configure script
        run: |
          libtoolize
          aclocal
          autoheader
          autoconf
          automake --add-missing
      - name: Create output folder
        run: mkdir output
      - name: Create zip
        run: zip -r output/${release_name}.zip . -x '*.git*' -x '*output*'
      - name: Create tar
        working-directory: ./output
        run: tar -czf ${release_name}.tar.gz --exclude=output --exclude=.git ../*
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ github.event.repository.name }} ${{ github.ref_name }}
          files: output/*
